MvcPL/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcPL.ViewModels
{
    public class UserViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public ICollection<RoleViewModel> Roles { get; set; }
        public UserInformationViewModel Profile { get; set; }
    }
}

MvcPL/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interfaces.Entities;
using BLL.Interfaces.Interfaces;
using MvcPL.Infastructure.Mappers;
using MvcPL.ViewModels;

namespace MvcPL.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IUserInformationService _informationServiceService;
        private readonly IPhotoService _photoService;
        private readonly IUserService _userService;
        public ProfileController(IUserInformationService userInformationService, IPhotoService photoService, IUserService userService)
        {
            if (ReferenceEquals(userInformationService, null))
                throw new ArgumentNullException(nameof(userInformationService));
            if (ReferenceEquals(photoService, null))
                throw new ArgumentNullException(nameof(photoService));
            if (ReferenceEquals(userService, null))
                throw new ArgumentNullException(nameof(userService));
            _informationServiceService = userInformationService;
            _photoService = photoService;
            _userService = userService;
        }

        /// <summary>
        /// Show profile user
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult ShowProfile(string userName, int page = 1)
        {
            IEnumerable<PhotoViewModel> photos = null;
            try
            {
                photos = _photoService.AllUserPhotos(userName).Select(t => t.ToMVCPhoto());
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            int pageSize = 12;

            var ivm = new IndexViewModel<PhotoViewModel>(page, pageSize, photos);
            var profile = new ProfileViewModel
            {
                UserInformation = _informationServiceService.GetByUserId(_userService.GetUserByName(userName).Id).ToMVCInformationUsers(),
                AllUserPhotos = ivm,
                UserName = userName
            };
            return View(profile);
        }

        /// <summary>
        /// Edit user profile
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditProfile()
        {
            return View();
        }

        /// <summary>
        /// Edit user profile Post
        /// </summary>

        public ActionResult EditProfile(EditUserInformation information, HttpPostedFileBase uploadImage)
        {
            UserInformationEntity profile = null;
            try
            {
                profile = _informationServiceService.GetByUserId(_userService.GetUserByName(User.Identity.Name).Id);
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }

            byte[] imageData = null;

            using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            {
                imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            }

            profile.Avatar = imageData;
            profile.FirstName = information.FirstName ?? profile.FirstName;
            profile.LastName = information.LastName ?? profile.LastName;
            profile.Age = information.Age == 0 ? profile.Age : information.Age;

            _informationServiceService.Update(profile);
            return RedirectToAction("ShowProfile", new { userName = User.Identity.Name });
        }
    }
}

MvcPL/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interfaces.Interfaces;
using BLL.Services;
using MvcPL.Infastructure.Mappers;
using MvcPL.ViewModels;

namespace MvcPL.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IUserInformationService _userInformationService;
        public UserController(IUserService userService, IUserInformationService userInformationService)
        {
            if (ReferenceEquals(userService, null))
                throw new ArgumentNullException(nameof(userService));
            if (ReferenceEquals(userInformationService, null))
                throw new ArgumentNullException(nameof(userService));

            _userInformationService = userInformationService;
            _userService = userService;
        }

        /// <summary>
        /// Shows users
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Index(int page = 1)
        {
            List<UserViewModel> users = null;
            try
            {
                users = _userService.GetAll().Select(user => user.ToMVCUser()).ToList();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            foreach (var u in users)
            {
                try
                {
                    u.Profile = _userInformationService.GetByUserId(u.Id).ToMVCInformationUsers();
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
            }
            int pageSize = 10;

            var ivm = new IndexViewModel<UserViewModel>(page, pageSize, users);
            if (Request.IsAjaxRequest())
                return PartialView(ivm);
            return View(ivm);
        }


        /// <summary>
        /// Delete users
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            UserViewModel user = null;
            try
            {
                user = _userService.GetById(id)?.ToMVCUser();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (ReferenceEquals(user, null))
                RedirectToAction("Error", "Error");
            return View(user);
        }

        /// <summary>
        /// /Delete users Post
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _userService.Delete(_userService.GetById(user.Id));
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }

    }
}

MvcPL/Views/User/Delete.cshtml
@model MvcPL.ViewModels.UserViewModel
@{
    ViewBag.Title = "DeleteUser";
}

<h2>User delete</h2>
<div>Are you sure you want to delete user with login <b>@Html.DisplayFor(model => model.Name)</b>?</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" />
    </p>
    <p>
        @Html.ActionLink("Back to user's list", "Index")
    </p>
}

MvcPL/Views/User/Edit.cshtml
@model MvcPL.ViewModels.EditUserViewModel
@{
    ViewBag.Title = "Edit user";
}

<table class="table">
    <tr>
        <td> User name</td>
        <td> User E-mail</td>
        <td>Id</td>
        <td>Roles</td>

        <h2>All users</h2>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.AllRoles, new SelectList( Model.AllRoles.Select(t=>t.RoleName)))
        </div>
        }
        </tr>
    </table>

MvcPL/Views/User/Index.cshtml
@model MvcPL.ViewModels.IndexViewModel<MvcPL.ViewModels.UserViewModel>
@using MvcPL.Infastructure.Helpers


<head>
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
</head>

<div id="users-page">

    <table class="table">
        <tr>
            @foreach (var user in Model.Items)
            {
            <tr>
                <td>
                    @{
                        var base64 = Convert.ToBase64String(user.Profile.Avatar);
                        var imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                        <img src="@imgSrc" alt="Avatar" class="avatar-photo-mini" />
                    }
                </td>
                <td><a class="btn-success" href="@Url.Action("ShowProfile", "Profile",new { userName = user.Name },null)"> @user.Name</a></td>
                <td> @user.Email</td>
                @if (User.IsInRole("Administrator"))
                {

                    <td>
                        @foreach (var roles in user.Roles)
                        {
                            <p>@roles.RoleName</p>

                        }
                    </td>
                    <td> @Html.ActionLink("Delete", "Delete", new { id = user.Id })</td>
                }
            </tr>
                        }
            </tr>
        </table>
        <div class="pagination-cl">
            @using (Ajax.BeginForm("Index", "User", new AjaxOptions { UpdateTargetId = "users-page" }))
            {
                @Html.PageLinks(Model.PageInfo)
            }
        </div>
    </div>
    @section Scripts {
        @Scripts.Render("~/scripts/jquery-1.10.2.js")
        @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
        @Scripts.Render("~/Scripts/jquery-ui-1.12.0.min.js")
    }